name: Create YouTube Plus app
on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "The direct URL to the decrypted IPA file"
        default: ""
        required: true
        type: string
      tweak_version:
        description: "The version of the tweak to use. Enter the version manually from dayanch96/YTLite/releases or leave default"
        default: "5.0"
        required: true
        type: string
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build YouTube Plus
    runs-on: macos-12
    permissions:
      contents: write
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.1
        with:
          path: main
          submodules: recursive
      - name: Install Dependencies
        run: brew install ldid dpkg make coreutils
      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
      - name: Cache Azule
        id: azule_cache
        uses: actions/cache@v4.0.1
        env:
          cache-name: azule-cache
        with:
          path: ${{ github.workspace }}/Azule
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}
      - name: Clone Azule Repository
        if: steps.azule_cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/Al4ise/Azule ${{ github.workspace }}/Azule
      - name: Download YouTube
        id: download_youtube
        run: wget "${{ inputs.ipa_url }}" --no-verbose -O ${{ github.workspace }}/youtube.ipa
      - name: Download YouTube Plus
        id: download_ytp
        run: |
          deb_url="https://github.com/dayanch96/YTLite/releases/download/v${{ inputs.tweak_version }}/com.dvntm.ytlite_${{ inputs.tweak_version }}_iphoneos-arm.deb"
          wget "$deb_url" --no-verbose -O ${{ github.workspace }}/ytplus.deb
      - name: Inject tweak into IPA
        run: |
          cd ${{ github.workspace }}
          ./Azule/azule -n YouTubePlus -i ${{ github.workspace }}/youtube.ipa -o ${{ github.workspace }} -f ${{ github.workspace }}/ytplus.deb
      - name: Remove the Watch folder
        run: |
          cd ${{ github.workspace }}
          mv YouTubePlus.ipa YouTubePlus.zip
          unzip -q YouTubePlus.zip
          cd Payload/Youtube.app
          rm -rf Watch
          cd ../..
      - name: Download and add YoutubeExtensions
        run: |
          cd ${{ github.workspace }}
          wget https://github.com/CokePokes/YoutubeExtensions/archive/refs/heads/main.zip -O extensions.zip
          unzip -q extensions.zip
          mkdir -p Payload/Youtube.app/Plugins
          cp -R YoutubeExtensions-main/*.appex Payload/Youtube.app/Plugins/
      - name: Repackage IPA
        run: |
          cd ${{ github.workspace }}
          zip -qr YouTubePlus.ipa Payload
          rm -rf Payload extensions.zip YoutubeExtensions-main
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2.0.1
        with:
          tag_name: v${{ github.run_number }}
          name: YouTubePlus-v${{ github.run_number }}
          files: YouTubePlus.ipa
          draft: true
